# This is a basic workflow to help you get started with Actions

name: scrape_tweets

# Controls when the workflow will run
on:
  schedule:
        - cron: '0 12 * * *' #runs every hour

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
          - name: checkout repo content
            uses: actions/checkout@master # checkout the repository content to github runner.
          - name: setup python
            uses: actions/setup-python@v2
          - name: setup dependencies
            run: |
              pip install snscrape
              pip install pandas
              pip install python-csv
          - name: execute py script # run the run.py to get the latest data
            run: |
              python Peter_Obi_tweets.py
          - name: Commit and push if it changed
            run: |
              git config user.name actions-user
              git config user.email "actions@github.com"
              git add -A
              timestamp=$(date -u)
              git commit -m "Scrapped: ${timestamp} (auto)" 
              git push origin main
            env: 
              REPO_KEY: ${{secrets.GITHUB_TOKEN}}
              username: github-actions
