# This is a basic workflow to help you get started with Actions

name: scrape_tweets

# Controls when the workflow will run
on:
  schedule:
        - cron: '0 */12 * * *' #runs every 12 hour

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
          - name: checkout repo content
            uses: actions/checkout@v2 # checkout the repository content to github runner.
            
          - name: Set up python
            uses: actions/setup-python@v2
            with:
              python-version: 3.8
         
          - name: Install dependencies
            run: |
              python -m pip install --upgrade pip
              pip install -r requirements.txt
              
          - name: execute script
            run: python Peter_Obi_tweets.py
          - name: Commit and push if it change
            run: |
              git config user.name actions-user
              git config user.email "actions@github.com"
              git add -A
              timestamp=$(date -u)
              git commit -m "Scrapped: ${timestamp} (auto)" 
              git push origin main
            env: 
              REPO_KEY: ${{secrets.GITHUB_TOKEN}}
              username: github-actions
